version: '3.11'

services:

  web:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    volumes:
      - ./src:/app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
    stdin_open: true
    tty: true
