# Generated by Django 4.2.2 on 2023-09-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_access_user_alter_lessonview_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='duration_seconds',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='lessonview',
            name='view_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(to='api.product'),
        ),
        migrations.AddField(
            model_name='lessonview',
            name='duration_view',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
