# Generated by Django 4.2.2 on 2023-09-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_duration_seconds_lesson_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
