# Generated by Django 4.2.2 on 2023-09-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lesson_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='last_view',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
