# Generated by Django 4.2.2 on 2023-09-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lessonview_last_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='duration_view',
            field=models.IntegerField(default=0),
        ),
    ]
