# Generated by Django 4.2.2 on 2023-09-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
