# Generated by Django 4.2.2 on 2023-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_lesson_products_productaccess_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaccess',
            name='lessons',
        ),
        migrations.AddField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(related_name='products', to='api.lesson'),
        ),
    ]
